### ISSUE TITLE
Create components from response / requestBody / paramenters

### ISSUE THREAD

**Issue by dickermoshe** [tazatechnology/openapi_spec#48]
@walsha2 

Just wanted to start off and say that this is by far the best generator I've come across! I want to put in work so that it's more popular and easier to use.

I started working on a PR that would add a CLI to this package, but then realized that this package doesn't generate anything for the components that are declared in the path Items itself, this is a major downer :(

So...
1. Are you interested in a PR that adds a CLI to the package
2. Are you interested in a PR that would convert all the schemas declared in `pathitems` to a reference?

(EDIT)
Well, too late:
https://github.com/tazatechnology/openapi_spec/pull/49

**Comment by walsha2** [comment]
> Well, too late

Ha no worries!

> Just wanted to start off and say that this is by far the best generator I've come across

Yea I agree 😄. I used the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) for Dart and it was a mess. So opted to roll my own to better handle the edge cases and nuances of the OpenAPI spec.

On the todo list is better docs and more examples to help advertise this generator. Pretty bare right now. As it goes with OSS, time is always the issue. 

I'll try to prioritize this here soon because I genuinely use this repo almost every week to generate client Dart code for a variety of APIs I maintain.
